Working mean calculation

diff --git a/matrix b/matrix
--- a/matrix
+++ b/matrix
@@ -1,7 +1,14 @@
 #!/bin/bash
 
+dimsFile="dimsTemp.$$"
+transposeFile="transposeTemp.$$"
+cutFile="cutTemp.$$"
+meanFile="meanTemp.$$"
+calcMeanFile="calcMeanTemp.$$"
+
+trap 'rm -f $dimsFile $transposeFile $cutFile $meanFile $calcMeanFile' INT HUP TERM EXIT
+
 getDims() {
-  dimsFile="dimsTemp.$$"
   if [ "$#" -eq "0" ]
   then
     cat > "$dimsFile"
@@ -21,12 +28,9 @@ getDims() {
   rowCount=$(wc -l < "$dimsFile")
   colCount=$(head -1 < "$dimsFile" | tr '\t' '\n' | wc -l)
   echo "$rowCount" "$colCount"
-  rm -f "$dimsFile" #DEBUG
 }
 
 transposeMatrix() {
-  transposeFile="transposeTemp.$$"
-  cutFile="cutTemp.$$"
   if [ "$#" -eq "0" ]
   then
     cat > "$transposeFile"
@@ -43,34 +47,35 @@ transposeMatrix() {
 
   fi
 
-  rowCount=$(getDims "$transposeFile" | cut -f1 -d" ")
-  colCount=$(getDims "$transposeFile" | cut -f2 -d" ")
+  totalCols=$(getDims "$transposeFile" | cut -f2 -d" ")
   colToWrite=1
-  for ((colToRead = 1; colToRead <= colCount; colToRead++))
+
+  for ((colToRead = 1; colToRead <= totalCols; colToRead++))
   do
+
     while read -r line
     do
       [ "$colToWrite" -ne "1" ] && printf "\t" >> "$cutFile"
       printf "%d" "$(echo -n "$line" | cut -d$'\t' -f$colToRead)" >> "$cutFile"
       ((colToWrite++))
     done < "$transposeFile"
+
     printf '\n' >> "$cutFile"
     # Reset the column we're writing to so we can tab before printing an integer
     # in all columns after the first column
     colToWrite=1
   done
+
   cat "$cutFile"
-  rm -f "$transposeFile" #DEBUG
-  rm -f "$cutFile" #DEBUG
 }
 
 getMean() {
-  meanFile="meanTemp.$$"
   if [ "$#" -eq "0" ]
   then
     cat > "$meanFile"
   else
     checkParameters 1 "$@"
+
     if [ ! -r "$1" ]
     then
       echo "The file specified does not exist." >&2
@@ -78,20 +83,47 @@ getMean() {
     else
       cat "$1" > "$meanFile"
     fi
+
   fi
 
-  rm -f "$meanFile" #DEBUG
+  totalRows=$(getDims "$meanFile" | cut -f1 -d" ")
+  totalCols=$(getDims "$meanFile" | cut -f2 -d" ")
+  colToWrite=1
+
+  for ((colToRead = 1; colToRead <= totalCols; colToRead++))
+  do
+    sum=0
+
+    while read -r line
+    do
+      (( sum += "$(echo -n "$line" | cut -d$'\t' -f$colToRead)" ))
+    done < "$meanFile"
+
+    avg=$((($sum + ($totalRows/2)*( ($sum>0)*2-1 )) / $totalRows))
+    printf "%d" "$avg" >> "$calcMeanFile"
+    [ "$colToWrite" -ne "$totalCols" ] && printf "\t" >> "$calcMeanFile"
+    ((colToWrite++))
+  done
+
+  printf '\n' >> "$calcMeanFile"
+
+  cat "$calcMeanFile"
 }
 
-addMatrix() {
+addMatrices() {
   [ ! -r "$1" ] || [ ! -r "$2" ] && { echo "We couldn't detect one or both of the supplied matrices" >&2; exit 10; }
-  [ "$(getDims "$1")" != "$(getDims "$2")" ] && { echo "We couldn't perform this operation on matrices of different dimensions." >&2; exit 11; }
-  echo "Good to add!" #TODO
+  [ "$(getDims "$1")" != "$(getDims "$2")" ] && { echo "We couldn't perform this operation on matrices of incompatible dimensions." >&2; exit 11; }
+
+  totalRows=$(getDims "$1" | cut -f1 -d" ")
+  totalCols=$(getDims "$1" | cut -f2 -d" ")
+
+
+
 }
 
-multiplyMatrix() {
+multiplyMatrices() {
   [ ! -r "$1" ] || [ ! -r "$2" ] && { echo "We couldn't detect one or both of the supplied matrices" >&2; exit 10; }
-  [ "$(getDims "$1")" != "$(getDims "$2")" ] && { echo "We couldn't perform this operation on matrices of different dimensions." >&2; exit 11; }
+  [ "$(getDims "$1" | cut -f2 -d" ")" -ne "$(getDims "$2" | cut -f1 -d" ")" ] && { echo "We couldn't perform this operation on matrices of incompatible dimensions." >&2; exit 11; }
   echo "Good to multiply!" #TODO
 }
 
@@ -113,11 +145,11 @@ getCommand() {
     ;;
     add)
       checkParameters 2 "${@:2}"
-      addMatrix "${@:2}"
+      addMatrices "${@:2}"
     ;;
     multiply)
       checkParameters 2 "${@:2}"
-      multiplyMatrix "${@:2}"
+      multiplyMatrices "${@:2}"
     ;;
     *)
       echo "Invalid argument" >&2; exit 2
